from enum import Enum


class ConfigEnvNames(Enum):
    TELEGRAM_BOT_API_ENVIRONMENT_NAME = "5845797747:AAECXtBR5zUZPE2c8SNBCEVeKFg6GNniw6g"
    OPENAI_API_ENVIRONMENT_NAME = "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"

    DB_PATH = "DB_PATH"

    LOG_LEVEL = "LOG_LEVEL"
    LOG_FILE = "LOG_FILE"

    GPT_MODEL = "GPT_MODEL"
